build:
    image: default-jammy
    environment:
        php: '8.1'
        node: 'v18.17'

    dependencies:
        before:
            - 'npm cache clean --force'
            - 'rm -rf node_modules'
            - 'npm install'
            - 'npm install fast-glob --save'

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
