build:
    image: default-jammy
    environment:
        php: '8.1'
        node: 'v20.0'

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
